CREATE TABLE tb_missoes (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nome VARCHAR(255),
                            ranking VARCHAR(255)
);

CREATE TABLE tb_cadastro (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nome VARCHAR(255),
                             email VARCHAR(255) UNIQUE,
                             idade INTEGER,
                             rank VARCHAR(255),
                             missoes_id BIGINT,

                             CONSTRAINT fk_cadastro_missao
                                 FOREIGN KEY (missoes_id)
                                     REFERENCES tb_missoes(id)
);